//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_GameSense.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_GameSense.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7
        ///#,Singular,,Plural,,StartsWithVowel,,,
        ///int32,str,sbyte,str,sbyte,sbyte,sbyte,sbyte,sbyte
        ///0,&quot;&quot;,0,&quot;&quot;,0,0,1,0,0
        ///1,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0
        ///2,&quot;ruins runner&quot;,0,&quot;ruins runners&quot;,0,0,1,0,0
        ///3,&quot;antelope doe&quot;,0,&quot;antelope does&quot;,0,1,1,0,0
        ///4,&quot;antelope stag&quot;,0,&quot;antelope stags&quot;,0,1,1,0,0
        ///5,&quot;opo-opo&quot;,0,&quot;opo-opos&quot;,0,1,1,0,0
        ///6,&quot;lemur&quot;,0,&quot;lemurs&quot;,0,0,1,0,0
        ///7,&quot;giant gnat&quot;,0,&quot;giant gnats&quot;,0,0,1,0,0
        ///8,&quot;ked&quot;,0,&quot;keds&quot;,0,0,1,0,0
        ///9,&quot;miteling&quot;,0,&quot;mitelings&quot;,0,0,1,0,0
        ///10,&quot;diremite&quot;,0,&quot;diremites&quot;,0,0,1,0,0
        ///11, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BNpcName {
            get {
                return ResourceManager.GetString("BNpcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77
        ///#,,,,InstanceContent,,,,,,ContentMemberType,,,,,,ClassJobLevel{Required},ClassJobLevel{Sync},ItemLevel{Required},ItemLevel{Sync},,,,,,ContentIndicator,,,,,,,,,,,,,Icon,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///int32,str,uint16,byte,InstanceContent,bit&amp;01,byte,uint32,uint32,byte,Conte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentFinderCondition {
            get {
                return ResourceManager.GetString("ContentFinderCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5671|612|-464|-488
        ///5672|612|-12|-533
        ///5674|612|70|-245
        ///5675|612|-603|-301
        ///5676|612|-496|-410
        ///5677|612|-12|-533
        ///5678|612|332|-318
        ///5679|612|176|-287
        ///5680|612|-191|-584
        ///5681|612|-261|99
        ///5682|612|-261|99
        ///5683|612|-541|-166
        ///5684|612|-475|77
        ///5685|612|-550|355
        ///5686|612|-631|434
        ///5687|612|-517|102
        ///5688|612|678|-157
        ///5689|612|634|-85
        ///5690|612|634|-85
        ///5691|612|634|-85
        ///5692|612|482|-245
        ///5693|612|383|98
        ///5694|612|451|329
        ///5695|612|763|330
        ///5696|612|382|440
        ///5697|612|194|428
        ///5698|620|-75|-346
        ///5699|62 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DailyHunts {
            get {
                return ResourceManager.GetString("DailyHunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette result: {0}.
        /// </summary>
        public static string DutyRouletteResult {
            get {
                return ResourceManager.GetString("DutyRouletteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon enemy {
            get {
                object obj = ResourceManager.GetObject("enemy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to signature scan ({0})..
        /// </summary>
        public static string FailedToSigScan {
            get {
                return ResourceManager.GetString("FailedToSigScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33
        ///#,EurekaFate,,Location,ClassJobLevel,ClassJobLevel{Max},EventItem,,,,,Icon{Objective},Icon{Map},,Music,,,,,,,,,,,,,,Name,Description,Objective,StatusText[0],StatusText[1],StatusText[2],ArrayIndex
        ///int32,byte,byte,uint32,byte,byte,EventItem,uint16,byte,byte,byte,Image,Image,uint32,BGM,uint32,uint32,uint16,uint16,uint16,bit&amp;01,bit&amp;02,bit&amp;04,uint16,bit&amp;08,bit&amp;10,bit&amp;20,uint32,str,str,str,str,str,str,ArrayEventHandl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fate {
            get {
                return ResourceManager.GetString("Fate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announce.
        /// </summary>
        public static string FATEListViewAnnounce {
            get {
                return ResourceManager.GetString("FATEListViewAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string FATEListViewIcon {
            get {
                return ResourceManager.GetString("FATEListViewIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string FATEListViewLevel {
            get {
                return ResourceManager.GetString("FATEListViewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FATEListViewName {
            get {
                return ResourceManager.GetString("FATEListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string FATEListViewZones {
            get {
                return ResourceManager.GetString("FATEListViewZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATE: {0} @.
        /// </summary>
        public static string FATEMsg {
            get {
                return ResourceManager.GetString("FATEMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% with {1}:{2} remaining.
        /// </summary>
        public static string FATEPrcTimeRemaining {
            get {
                return ResourceManager.GetString("FATEPrcTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announce FATE once every.
        /// </summary>
        public static string FormAnnounceFateEveryPercentage {
            get {
                return ResourceManager.GetString("FormAnnounceFateEveryPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only once; when found and dead.
        /// </summary>
        public static string FormAnnounceOncePerHunt {
            get {
                return ResourceManager.GetString("FormAnnounceOncePerHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Ranks.
        /// </summary>
        public static string FormARanks {
            get {
                return ResourceManager.GetString("FormARanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARR.
        /// </summary>
        public static string FormARRAbrv {
            get {
                return ResourceManager.GetString("FormARRAbrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Ranks.
        /// </summary>
        public static string FormBRanks {
            get {
                return ResourceManager.GetString("FormBRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string FormConnectedTo {
            get {
                return ResourceManager.GetString("FormConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0} with {1} other users.
        /// </summary>
        public static string FormConnectedToCount {
            get {
                return ResourceManager.GetString("FormConnectedToCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string FormConnecting {
            get {
                return ResourceManager.GetString("FormConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect. Retrying in {0} seconds..
        /// </summary>
        public static string FormConnectingRetrying {
            get {
                return ResourceManager.GetString("FormConnectingRetrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not announce FATE if minutes remaining is below:.
        /// </summary>
        public static string FormDoNotAnnounceFateIfMinutesRemaining {
            get {
                return ResourceManager.GetString("FormDoNotAnnounceFateIfMinutesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roulette results.
        /// </summary>
        public static string FormDutyRoulette {
            get {
                return ResourceManager.GetString("FormDutyRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not join world. Ensure that {0} is verified on XIVHunt.net.
        /// </summary>
        public static string FormFailedToJoin {
            get {
                return ResourceManager.GetString("FormFailedToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FATEs selected.
        /// </summary>
        public static string FormFATEPlural {
            get {
                return ResourceManager.GetString("FormFATEPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATE Presets.
        /// </summary>
        public static string FormFATEPresets {
            get {
                return ResourceManager.GetString("FormFATEPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATEs:.
        /// </summary>
        public static string FormFATEs {
            get {
                return ResourceManager.GetString("FormFATEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FATE selected.
        /// </summary>
        public static string FormFATESingle {
            get {
                return ResourceManager.GetString("FormFATESingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash FFXIV taskbar icon on DF pops.
        /// </summary>
        public static string FormFlashTaskbarIconDF {
            get {
                return ResourceManager.GetString("FormFlashTaskbarIconDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash FFXIV taskbar icon on hunt and FATE announcements.
        /// </summary>
        public static string FormFlashTaskbarIconHuntFate {
            get {
                return ResourceManager.GetString("FormFlashTaskbarIconHuntFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget on zone change.
        /// </summary>
        public static string FormForgetOnZoneChange {
            get {
                return ResourceManager.GetString("FormForgetOnZoneChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HW.
        /// </summary>
        public static string FormHWAbrv {
            get {
                return ResourceManager.GetString("FormHWAbrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} account, with a verified character on {1}, is required..
        /// </summary>
        public static string FormLogin {
            get {
                return ResourceManager.GetString("FormLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA code if applicable:.
        /// </summary>
        public static string FormLogin2FA {
            get {
                return ResourceManager.GetString("FormLogin2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        public static string FormLoginEmail {
            get {
                return ResourceManager.GetString("FormLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string FormLoginFailed {
            get {
                return ResourceManager.GetString("FormLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} account is required..
        /// </summary>
        public static string FormLoginKRCN {
            get {
                return ResourceManager.GetString("FormLoginKRCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string FormLoginLogin {
            get {
                return ResourceManager.GetString("FormLoginLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string FormLoginPassword {
            get {
                return ResourceManager.GetString("FormLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string FormMinimizeToTray {
            get {
                return ResourceManager.GetString("FormMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes between announcements for the same FATE:.
        /// </summary>
        public static string FormMinutesBetweenFateAnnouncements {
            get {
                return ResourceManager.GetString("FormMinutesBetweenFateAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes between announcements for the same hunt:.
        /// </summary>
        public static string FormMinutesBetweenHuntAnnouncements {
            get {
                return ResourceManager.GetString("FormMinutesBetweenHuntAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not announce while in content (DF).
        /// </summary>
        public static string FormNoAnnouncementsInContent {
            get {
                return ResourceManager.GetString("FormNoAnnouncementsInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find process or world. Please start {0} and log into a character..
        /// </summary>
        public static string FormNoProcess {
            get {
                return ResourceManager.GetString("FormNoProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to look for perform tracks:.
        /// </summary>
        public static string FormPerformDirectory {
            get {
                return ResourceManager.GetString("FormPerformDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity:.
        /// </summary>
        public static string FormRadarBackgroundOpacity {
            get {
                return ResourceManager.GetString("FormRadarBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banded coffers, hoards, cairns (Passage/Return).
        /// </summary>
        public static string FormRadarDisplayExtraDeepDungeon {
            get {
                return ResourceManager.GetString("FormRadarDisplayExtraDeepDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only display the following.
        /// </summary>
        public static string FormRadarDisplayGBH {
            get {
                return ResourceManager.GetString("FormRadarDisplayGBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        public static string FormRadarDisplayMonsters {
            get {
                return ResourceManager.GetString("FormRadarDisplayMonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other players characters.
        /// </summary>
        public static string FormRadarDisplayOtherPCs {
            get {
                return ResourceManager.GetString("FormRadarDisplayOtherPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own player character (self).
        /// </summary>
        public static string FormRadarDisplaySelf {
            get {
                return ResourceManager.GetString("FormRadarDisplaySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Coffers.
        /// </summary>
        public static string FormRadarDisplayTreasureCoffers {
            get {
                return ResourceManager.GetString("FormRadarDisplayTreasureCoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Coffers (Gold).
        /// </summary>
        public static string FormRadarDisplayTreasureCoffersGold {
            get {
                return ResourceManager.GetString("FormRadarDisplayTreasureCoffersGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Coffers (Silver).
        /// </summary>
        public static string FormRadarDisplayTreasureCoffersSilver {
            get {
                return ResourceManager.GetString("FormRadarDisplayTreasureCoffersSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable clickthru.
        /// </summary>
        public static string FormRadarEnableClickthru {
            get {
                return ResourceManager.GetString("FormRadarEnableClickthru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities opacity:.
        /// </summary>
        public static string FormRadarEntitiesOpacity {
            get {
                return ResourceManager.GetString("FormRadarEntitiesOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities scale:.
        /// </summary>
        public static string FormRadarEntitiesScale {
            get {
                return ResourceManager.GetString("FormRadarEntitiesScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock overlay.
        /// </summary>
        public static string FormRadarLockOverlay {
            get {
                return ResourceManager.GetString("FormRadarLockOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Framerate:.
        /// </summary>
        public static string FormRadarMaxFPS {
            get {
                return ResourceManager.GetString("FormRadarMaxFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string FormRadarZoom {
            get {
                return ResourceManager.GetString("FormRadarZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Server ID.
        /// </summary>
        public static string FormReadingSID {
            get {
                return ResourceManager.GetString("FormReadingSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        public static string FormSBAbrv {
            get {
                return ResourceManager.GetString("FormSBAbrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string FormSearchCoverText {
            get {
                return ResourceManager.GetString("FormSearchCoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new alert....
        /// </summary>
        public static string FormSFCMNewAlert {
            get {
                return ResourceManager.GetString("FormSFCMNewAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        public static string FormSFDialogFilter {
            get {
                return ResourceManager.GetString("FormSFDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a sound file to be played when a report is written to chat.
        /// </summary>
        public static string FormSFDialogTitle {
            get {
                return ResourceManager.GetString("FormSFDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S Ranks.
        /// </summary>
        public static string FormSRanks {
            get {
                return ResourceManager.GetString("FormSRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string FormTabCtrlNotifications {
            get {
                return ResourceManager.GetString("FormTabCtrlNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string FormTabCtrlPerformance {
            get {
                return ResourceManager.GetString("FormTabCtrlPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Radar.
        /// </summary>
        public static string FormTabCtrlRadar {
            get {
                return ResourceManager.GetString("FormTabCtrlRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FormToggleButtonOff {
            get {
                return ResourceManager.GetString("FormToggleButtonOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FormToggleButtonOn {
            get {
                return ResourceManager.GetString("FormToggleButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /hunt FATEName enables announcements of said FATE.
        /// </summary>
        public static string FormTrackFATEAfterQuery {
            get {
                return ResourceManager.GetString("FormTrackFATEAfterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the following in the chatbox.
        /// </summary>
        public static string GroupBoxHeader {
            get {
                return ResourceManager.GetString("GroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hunt {
            get {
                object obj = ResourceManager.GetObject("Hunt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hunt_x64 {
            get {
                object obj = ResourceManager.GetObject("Hunt_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Instance {0}.
        /// </summary>
        public static string HuntInstance {
            get {
                return ResourceManager.GetString("HuntInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rank: {1} @ &lt;pos&gt;.
        /// </summary>
        public static string HuntMsg {
            get {
                return ResourceManager.GetString("HuntMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rank: {1} was just killed..
        /// </summary>
        public static string HuntMsgKilled {
            get {
                return ResourceManager.GetString("HuntMsgKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can be found at .
        /// </summary>
        public static string LKICanBeFoundAt {
            get {
                return ResourceManager.GetString("LKICanBeFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was last reported {1} hours and {2} minutes ago at.
        /// </summary>
        public static string LKIFATE {
            get {
                return ResourceManager.GetString("LKIFATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was last reported {1} days ago..
        /// </summary>
        public static string LKIFATEDays {
            get {
                return ResourceManager.GetString("LKIFATEDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hours ago.
        /// </summary>
        public static string LKIHours {
            get {
                return ResourceManager.GetString("LKIHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hours and {1} minutes ago.
        /// </summary>
        public static string LKIHoursMinutes {
            get {
                return ResourceManager.GetString("LKIHoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was killed .
        /// </summary>
        public static string LKIHuntKilled {
            get {
                return ResourceManager.GetString("LKIHuntKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been reported yet..
        /// </summary>
        public static string LKIHuntNotReported {
            get {
                return ResourceManager.GetString("LKIHuntNotReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was last seen at .
        /// </summary>
        public static string LKILastSeenAt {
            get {
                return ResourceManager.GetString("LKILastSeenAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} minutes ago.
        /// </summary>
        public static string LKIMinutes {
            get {
                return ResourceManager.GetString("LKIMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
        ///#,,,,Hierarchy,MapMarkerRange,Id,SizeFactor,Offset{X},Offset{Y},PlaceName{Region},PlaceName,PlaceName{Sub},DiscoveryIndex,,TerritoryType,DiscoveryArrayByte,
        ///int32,byte,byte,sbyte,byte,uint16,str,uint16,int16,int16,PlaceName,PlaceName,PlaceName,int16,uint32,TerritoryType,bit&amp;01,bit&amp;02
        ///0,0,0,0,0,0,&quot;&quot;,100,0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,-1,0,,True,False
        ///1,0,0,0,1,0,&quot;default/00&quot;,100,0,0,&quot;???&quot;,&quot;Eorzea&quot;,&quot;&quot;,-1,0,&quot;&quot;,True,False
        ///2,2,2,0,1,3,&quot;f1t1/00&quot;,200,0,0,&quot;The Black Shroud&quot;,&quot;New Grid [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound alert.
        /// </summary>
        public static string NoSoundAlert {
            get {
                return ResourceManager.GetString("NoSoundAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Viewer.
        /// </summary>
        public static string OpenLogToolTip {
            get {
                return ResourceManager.GetString("OpenLogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string OpenSettingsToolTip {
            get {
                return ResourceManager.GetString("OpenSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3
        ///#,,,,
        ///int32,uint16,str,int32,byte
        ///0,0,&quot;&quot;,0,0
        ///1,6315,&quot;C (-1)&quot;,715,1
        ///2,6322,&quot;C♯ (-1)&quot;,722,4
        ///3,6316,&quot;D (-1)&quot;,716,7
        ///4,6323,&quot;E♭ (-1)&quot;,723,10
        ///5,6317,&quot;E (-1)&quot;,717,13
        ///6,6318,&quot;F (-1)&quot;,718,16
        ///7,6324,&quot;F♯ (-1)&quot;,724,19
        ///8,6319,&quot;G (-1)&quot;,719,22
        ///9,6325,&quot;G♯ (-1)&quot;,725,25
        ///10,6320,&quot;A (-1)&quot;,720,28
        ///11,6326,&quot;B♭ (-1)&quot;,726,31
        ///12,6321,&quot;B (-1)&quot;,721,34
        ///13,6327,&quot;C&quot;,701,2
        ///14,6334,&quot;C♯&quot;,709,5
        ///15,6328,&quot;D&quot;,702,8
        ///16,6335,&quot;E♭&quot;,710,11
        ///17,6329,&quot;E&quot;,703,14
        ///18,6330,&quot;F&quot;,704,17
        ///19,6336,&quot;F♯&quot;,711,20
        ///20,6331,&quot;G&quot;,705,23 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Perform {
            get {
                return ResourceManager.GetString("Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform directory was not found. Please specify one in XIV-Hunt settings.
        /// </summary>
        public static string PerformDirectoryNotExists {
            get {
                return ResourceManager.GetString("PerformDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string PerformListViewLastModified {
            get {
                return ResourceManager.GetString("PerformListViewLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PerformListViewName {
            get {
                return ResourceManager.GetString("PerformListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation state..
        /// </summary>
        public static string PreparationState {
            get {
                return ResourceManager.GetString("PreparationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33
        ///#,EventItem,MonsterNoteTarget{Common}[0],MonsterCount[0],MonsterNoteTarget{Common}[1],MonsterCount[1],MonsterNoteTarget{Common}[2],MonsterCount[2],MonsterNoteTarget{Common}[3],MonsterCount[3],MonsterNoteTarget{Common}[4],MonsterCount[4],MonsterNoteTarget{Common}[5],MonsterCount[5],MonsterNoteTarget{Common}[6],MonsterCount[6],MonsterNoteTarget{Common}[7],MonsterCount[7],MonsterNoteTarget{Common}[8],MonsterCount[8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RelicNote {
            get {
                return ResourceManager.GetString("RelicNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required for changes to take effect.
        /// </summary>
        public static string RestartForChanges {
            get {
                return ResourceManager.GetString("RestartForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string SettingsLogOut {
            get {
                return ResourceManager.GetString("SettingsLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you need to log in as a different user: .
        /// </summary>
        public static string SettingsNeedToLoginAsADifferentUser {
            get {
                return ResourceManager.GetString("SettingsNeedToLoginAsADifferentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33
        ///#,Name,Bg,,PlaceName{Region},PlaceName{Zone},PlaceName,Map,,,TerritoryIntendedUse,,,WeatherRate,,,,,,,,,,ArrayEventHandler,,Aetheryte,,,,,,,,,
        ///int32,str,str,byte,PlaceName,PlaceName,PlaceName,Map,byte,byte,byte,uint16,bit&amp;01,byte,bit&amp;02,byte,bit&amp;04,bit&amp;08,bit&amp;10,bit&amp;20,uint16,int32,int32,ArrayEventHandler,uint16,Aetheryte,int32,uint16,sbyte,bit&amp;40,byte,byte,byte,byte,bit&amp;80
        ///1,&quot;&quot;,&quot;&quot;,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,0,0,0,0,False, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TerritoryType {
            get {
                return ResourceManager.GetString("TerritoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been installed. It is recommended that you, from now on, start {0} via the shortcuts placed on your desktop and start menu..
        /// </summary>
        public static string ToastNotificationAppInstalledShortcut {
            get {
                return ResourceManager.GetString("ToastNotificationAppInstalledShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,0,1,2,3
        ///#,Name,,DataCenter,
        ///int32,str,byte,WorldDCGroupType,bit&amp;01
        ///0,&quot;crossworld&quot;,0,&quot;INVALID&quot;,False
        ///1,&quot;c-funereus&quot;,0,&quot;Gaia&quot;,False
        ///2,&quot;c-contents&quot;,0,&quot;INVALID&quot;,False
        ///3,&quot;c-whiteae&quot;,0,&quot;Elemental&quot;,False
        ///4,&quot;c-baudinii&quot;,0,&quot;INVALID&quot;,False
        ///5,&quot;c-contents2&quot;,0,&quot;Gaia&quot;,False
        ///16,&quot;konconv&quot;,0,&quot;INVALID&quot;,False
        ///23,&quot;Asura&quot;,1,&quot;Mana&quot;,True
        ///24,&quot;Belias&quot;,1,&quot;Mana&quot;,True
        ///25,&quot;Chaos&quot;,1,&quot;INVALID&quot;,True
        ///26,&quot;Hecatoncheir&quot;,1,&quot;INVALID&quot;,True
        ///27,&quot;Moomba&quot;,1,&quot;INVALID&quot;,True
        ///28,&quot;Pandaemonium&quot;,1,&quot;Mana&quot;,True
        ///29,&quot;Shinryu&quot;,1,&quot;Mana&quot;,Tru [rest of string was truncated]&quot;;.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
